apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pg-to-kafka.fullname" . }}
  labels: {{- include "pg-to-kafka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "pg-to-kafka.name" . }} }
  template:
    metadata:
      labels: { app: {{ include "pg-to-kafka.name" . }} }
    spec:
      containers:
        - name: listener
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k,$v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
